/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAiToolsRouteImport } from './routes/_authenticated/ai-tools'
import { Route as AuthenticatedAkunRouteImport } from './routes/_authenticated/akun'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedPasFotoRouteImport } from './routes/_authenticated/pas-foto'
import { Route as AuthenticatedPdfToolsRouteImport } from './routes/_authenticated/pdf-tools'
import { Route as AuthenticatedPhotoToolsRouteImport } from './routes/_authenticated/photo-tools'
import { Route as AuthenticatedRiwayatRouteImport } from './routes/_authenticated/riwayat'
import { Route as AuthenticatedWordToolsRouteImport } from './routes/_authenticated/word-tools'
import { Route as ApiEnhanceImageRouteImport } from './routes/api/enhance-image'
import { Route as ApiRemoveBackgroundRouteImport } from './routes/api/remove-background'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAiToolsRoute = AuthenticatedAiToolsRouteImport.update({
  id: '/ai-tools',
  path: '/ai-tools',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAkunRoute = AuthenticatedAkunRouteImport.update({
  id: '/akun',
  path: '/akun',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPasFotoRoute = AuthenticatedPasFotoRouteImport.update({
  id: '/pas-foto',
  path: '/pas-foto',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPdfToolsRoute = AuthenticatedPdfToolsRouteImport.update({
  id: '/pdf-tools',
  path: '/pdf-tools',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPhotoToolsRoute = AuthenticatedPhotoToolsRouteImport.update({
  id: '/photo-tools',
  path: '/photo-tools',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRiwayatRoute = AuthenticatedRiwayatRouteImport.update({
  id: '/riwayat',
  path: '/riwayat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWordToolsRoute = AuthenticatedWordToolsRouteImport.update({
  id: '/word-tools',
  path: '/word-tools',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiEnhanceImageRoute = ApiEnhanceImageRouteImport.update({
  id: '/api/enhance-image',
  path: '/api/enhance-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRemoveBackgroundRoute = ApiRemoveBackgroundRouteImport.update({
  id: '/api/remove-background',
  path: '/api/remove-background',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ai-tools': typeof AuthenticatedAiToolsRoute
  '/akun': typeof AuthenticatedAkunRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/pas-foto': typeof AuthenticatedPasFotoRoute
  '/pdf-tools': typeof AuthenticatedPdfToolsRoute
  '/photo-tools': typeof AuthenticatedPhotoToolsRoute
  '/riwayat': typeof AuthenticatedRiwayatRoute
  '/word-tools': typeof AuthenticatedWordToolsRoute
  '/api/enhance-image': typeof ApiEnhanceImageRoute
  '/api/remove-background': typeof ApiRemoveBackgroundRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ai-tools': typeof AuthenticatedAiToolsRoute
  '/akun': typeof AuthenticatedAkunRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/pas-foto': typeof AuthenticatedPasFotoRoute
  '/pdf-tools': typeof AuthenticatedPdfToolsRoute
  '/photo-tools': typeof AuthenticatedPhotoToolsRoute
  '/riwayat': typeof AuthenticatedRiwayatRoute
  '/word-tools': typeof AuthenticatedWordToolsRoute
  '/api/enhance-image': typeof ApiEnhanceImageRoute
  '/api/remove-background': typeof ApiRemoveBackgroundRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/ai-tools': typeof AuthenticatedAiToolsRoute
  '/_authenticated/akun': typeof AuthenticatedAkunRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/pas-foto': typeof AuthenticatedPasFotoRoute
  '/_authenticated/pdf-tools': typeof AuthenticatedPdfToolsRoute
  '/_authenticated/photo-tools': typeof AuthenticatedPhotoToolsRoute
  '/_authenticated/riwayat': typeof AuthenticatedRiwayatRoute
  '/_authenticated/word-tools': typeof AuthenticatedWordToolsRoute
  '/api/enhance-image': typeof ApiEnhanceImageRoute
  '/api/remove-background': typeof ApiRemoveBackgroundRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/ai-tools'
    | '/akun'
    | '/dashboard'
    | '/pas-foto'
    | '/pdf-tools'
    | '/photo-tools'
    | '/riwayat'
    | '/word-tools'
    | '/api/enhance-image'
    | '/api/remove-background'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/ai-tools'
    | '/akun'
    | '/dashboard'
    | '/pas-foto'
    | '/pdf-tools'
    | '/photo-tools'
    | '/riwayat'
    | '/word-tools'
    | '/api/enhance-image'
    | '/api/remove-background'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/ai-tools'
    | '/_authenticated/akun'
    | '/_authenticated/dashboard'
    | '/_authenticated/pas-foto'
    | '/_authenticated/pdf-tools'
    | '/_authenticated/photo-tools'
    | '/_authenticated/riwayat'
    | '/_authenticated/word-tools'
    | '/api/enhance-image'
    | '/api/remove-background'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiEnhanceImageRoute: typeof ApiEnhanceImageRoute
  ApiRemoveBackgroundRoute: typeof ApiRemoveBackgroundRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ai-tools': {
      id: '/_authenticated/ai-tools'
      path: '/ai-tools'
      fullPath: '/ai-tools'
      preLoaderRoute: typeof AuthenticatedAiToolsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/akun': {
      id: '/_authenticated/akun'
      path: '/akun'
      fullPath: '/akun'
      preLoaderRoute: typeof AuthenticatedAkunRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pas-foto': {
      id: '/_authenticated/pas-foto'
      path: '/pas-foto'
      fullPath: '/pas-foto'
      preLoaderRoute: typeof AuthenticatedPasFotoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pdf-tools': {
      id: '/_authenticated/pdf-tools'
      path: '/pdf-tools'
      fullPath: '/pdf-tools'
      preLoaderRoute: typeof AuthenticatedPdfToolsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/photo-tools': {
      id: '/_authenticated/photo-tools'
      path: '/photo-tools'
      fullPath: '/photo-tools'
      preLoaderRoute: typeof AuthenticatedPhotoToolsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/riwayat': {
      id: '/_authenticated/riwayat'
      path: '/riwayat'
      fullPath: '/riwayat'
      preLoaderRoute: typeof AuthenticatedRiwayatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/word-tools': {
      id: '/_authenticated/word-tools'
      path: '/word-tools'
      fullPath: '/word-tools'
      preLoaderRoute: typeof AuthenticatedWordToolsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/enhance-image': {
      id: '/api/enhance-image'
      path: '/api/enhance-image'
      fullPath: '/api/enhance-image'
      preLoaderRoute: typeof ApiEnhanceImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/remove-background': {
      id: '/api/remove-background'
      path: '/api/remove-background'
      fullPath: '/api/remove-background'
      preLoaderRoute: typeof ApiRemoveBackgroundRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAiToolsRoute: typeof AuthenticatedAiToolsRoute
  AuthenticatedAkunRoute: typeof AuthenticatedAkunRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPasFotoRoute: typeof AuthenticatedPasFotoRoute
  AuthenticatedPdfToolsRoute: typeof AuthenticatedPdfToolsRoute
  AuthenticatedPhotoToolsRoute: typeof AuthenticatedPhotoToolsRoute
  AuthenticatedRiwayatRoute: typeof AuthenticatedRiwayatRoute
  AuthenticatedWordToolsRoute: typeof AuthenticatedWordToolsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAiToolsRoute: AuthenticatedAiToolsRoute,
  AuthenticatedAkunRoute: AuthenticatedAkunRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPasFotoRoute: AuthenticatedPasFotoRoute,
  AuthenticatedPdfToolsRoute: AuthenticatedPdfToolsRoute,
  AuthenticatedPhotoToolsRoute: AuthenticatedPhotoToolsRoute,
  AuthenticatedRiwayatRoute: AuthenticatedRiwayatRoute,
  AuthenticatedWordToolsRoute: AuthenticatedWordToolsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiEnhanceImageRoute: ApiEnhanceImageRoute,
  ApiRemoveBackgroundRoute: ApiRemoveBackgroundRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
